[{"message":"new row for relation \"Users\" violates check constraint \"Users_balance_ck\"","time":"6:16:21 PM","code":"-","stackTrace":{"errorType":"SequelizeDatabaseError","path":["    at Query.formatError (/server/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)","    at Query.run (/server/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async /server/node_modules/sequelize/lib/sequelize.js:619:16","    at async PostgresQueryInterface.bulkUpdate (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:882:12)","    at async Function.update (/server/node_modules/sequelize/lib/model.js:3175:28)","    at async Object.module.exports.updateUser (/server/src/server/controllers/queries/userQueries.js:7:41)","    at async module.exports.cashout (/server/src/server/controllers/userController.js:130:25)"]}},{"message":"new row for relation \"Users\" violates check constraint \"Users_balance_ck\"","time":"6:11:50 PM","code":"-","stackTrace":"SequelizeDatabaseError: new row for relation \"Users\" violates check constraint \"Users_balance_ck\"\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.bulkUpdate (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:882:12)\n    at async Function.update (/server/node_modules/sequelize/lib/model.js:3175:28)\n    at async Object.module.exports.updateUser (/server/src/server/controllers/queries/userQueries.js:7:41)\n    at async module.exports.cashout (/server/src/server/controllers/userController.js:130:25)"},{"message":"new row for relation \"Users\" violates check constraint \"Users_balance_ck\"","time":"6:10:29 PM","code":"-","stackTrace":"SequelizeDatabaseError: new row for relation \"Users\" violates check constraint \"Users_balance_ck\"\n    at Query.formatError (/server/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/server/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /server/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.bulkUpdate (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:882:12)\n    at async Function.update (/server/node_modules/sequelize/lib/model.js:3175:28)\n    at async Object.module.exports.updateUser (/server/src/server/controllers/queries/userQueries.js:7:41)\n    at async module.exports.cashout (/server/src/server/controllers/userController.js:130:25)"},{"message":"Invalid credentials","time":"6:01:17 PM","code":401,"stackTrace":"UnauthorizedError: Invalid credentials\n    at module.exports.signIn (/server/src/server/controllers/authController.js:19:10)"}]